(define (domain khunpan02-gen)
  (:requirements :strips)
  (:predicates (adjwe ?h1 ?h2) (adjns ?v1 ?v2) 
        (at ?t ?h ?v) (empty ?h ?v) 
        (type_1 ?t) (type_2 ?t) (type_3 ?t) (type_4 ?t)
  )
  (:action move-type_1-s
   :parameters (?t ?x1 ?y1 ?y2)
   :precondition (and (type_1 ?t)
        (at ?t ?x1 ?y1)
        
        (adjns ?y1 ?y2)
        (empty ?x1 ?y2)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x1 ?y2) (not (empty ?x1 ?y2))
    )
  )
  (:action move-type_1-n
   :parameters (?t ?x1 ?y0 ?y1)
   :precondition (and (type_1 ?t)
        (at ?t ?x1 ?y1)
        
        (adjns ?y0 ?y1)
        (empty ?x1 ?y0)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x1 ?y0) (not (empty ?x1 ?y0))
    )
  )
  (:action move-type_1-e
   :parameters (?t ?x1 ?x2 ?y1)
   :precondition (and (type_1 ?t)
        (at ?t ?x1 ?y1)
        (adjwe ?x1 ?x2)
        
        (empty ?x2 ?y1)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x2 ?y1) (not (empty ?x2 ?y1))
    )
  )
  (:action move-type_1-w
   :parameters (?t ?x0 ?x1 ?y1)
   :precondition (and (type_1 ?t)
        (at ?t ?x1 ?y1)
        (adjwe ?x0 ?x1)
        
        (empty ?x0 ?y1)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x0 ?y1) (not (empty ?x0 ?y1))
    )
  )
  (:action move-type_2-s
   :parameters (?t ?x1 ?x2 ?y1 ?y2)
   :precondition (and (type_2 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x2 ?y1)
        (adjwe ?x1 ?x2)
        (adjns ?y1 ?y2)
        (empty ?x1 ?y2) (empty ?x2 ?y2)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x2 ?y1)) (empty ?x2 ?y1)
        (at ?t ?x1 ?y2) (not (empty ?x1 ?y2)) (at ?t ?x2 ?y2) (not (empty ?x2 ?y2))
    )
  )
  (:action move-type_2-n
   :parameters (?t ?x1 ?x2 ?y0 ?y1)
   :precondition (and (type_2 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x2 ?y1)
        (adjwe ?x1 ?x2)
        (adjns ?y0 ?y1)
        (empty ?x1 ?y0) (empty ?x2 ?y0)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x2 ?y1)) (empty ?x2 ?y1)
        (at ?t ?x1 ?y0) (not (empty ?x1 ?y0)) (at ?t ?x2 ?y0) (not (empty ?x2 ?y0))
    )
  )
  (:action move-type_2-e
   :parameters (?t ?x1 ?x2 ?x3 ?y1)
   :precondition (and (type_2 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x2 ?y1)
        (adjwe ?x1 ?x2) (adjwe ?x2 ?x3)
        
        (empty ?x3 ?y1)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x3 ?y1) (not (empty ?x3 ?y1))
    )
  )
  (:action move-type_2-w
   :parameters (?t ?x0 ?x1 ?x2 ?y1)
   :precondition (and (type_2 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x2 ?y1)
        (adjwe ?x0 ?x1) (adjwe ?x1 ?x2)
        
        (empty ?x0 ?y1)
    )
   :effect (and 
        (not (at ?t ?x2 ?y1)) (empty ?x2 ?y1)
        (at ?t ?x0 ?y1) (not (empty ?x0 ?y1))
    )
  )
  (:action move-type_3-s
   :parameters (?t ?x1 ?y1 ?y2 ?y3)
   :precondition (and (type_3 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2)
        
        (adjns ?y1 ?y2) (adjns ?y2 ?y3)
        (empty ?x1 ?y3)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x1 ?y3) (not (empty ?x1 ?y3))
    )
  )
  (:action move-type_3-n
   :parameters (?t ?x1 ?y0 ?y1 ?y2)
   :precondition (and (type_3 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2)
        
        (adjns ?y0 ?y1) (adjns ?y1 ?y2)
        (empty ?x1 ?y0)
    )
   :effect (and 
        (not (at ?t ?x1 ?y2)) (empty ?x1 ?y2)
        (at ?t ?x1 ?y0) (not (empty ?x1 ?y0))
    )
  )
  (:action move-type_3-e
   :parameters (?t ?x1 ?x2 ?y1 ?y2)
   :precondition (and (type_3 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2)
        (adjwe ?x1 ?x2)
        (adjns ?y1 ?y2)
        (empty ?x2 ?y1) (empty ?x2 ?y2)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x1 ?y2)) (empty ?x1 ?y2)
        (at ?t ?x2 ?y1) (not (empty ?x2 ?y1)) (at ?t ?x2 ?y2) (not (empty ?x2 ?y2))
    )
  )
  (:action move-type_3-w
   :parameters (?t ?x0 ?x1 ?y1 ?y2)
   :precondition (and (type_3 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2)
        (adjwe ?x0 ?x1)
        (adjns ?y1 ?y2)
        (empty ?x0 ?y1) (empty ?x0 ?y2)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x1 ?y2)) (empty ?x1 ?y2)
        (at ?t ?x0 ?y1) (not (empty ?x0 ?y1)) (at ?t ?x0 ?y2) (not (empty ?x0 ?y2))
    )
  )
  (:action move-type_4-s
   :parameters (?t ?x1 ?x2 ?y1 ?y2 ?y3)
   :precondition (and (type_4 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2) (at ?t ?x2 ?y1) (at ?t ?x2 ?y2)
        (adjwe ?x1 ?x2)
        (adjns ?y1 ?y2) (adjns ?y2 ?y3)
        (empty ?x2 ?y3) (empty ?x1 ?y3)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x2 ?y1)) (empty ?x2 ?y1)
        (at ?t ?x2 ?y3) (not (empty ?x2 ?y3)) (at ?t ?x1 ?y3) (not (empty ?x1 ?y3))
    )
  )
  (:action move-type_4-n
   :parameters (?t ?x1 ?x2 ?y0 ?y1 ?y2)
   :precondition (and (type_4 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2) (at ?t ?x2 ?y1) (at ?t ?x2 ?y2)
        (adjwe ?x1 ?x2)
        (adjns ?y0 ?y1) (adjns ?y1 ?y2)
        (empty ?x1 ?y0) (empty ?x2 ?y0)
    )
   :effect (and 
        (not (at ?t ?x1 ?y2)) (empty ?x1 ?y2) (not (at ?t ?x2 ?y2)) (empty ?x2 ?y2)
        (at ?t ?x1 ?y0) (not (empty ?x1 ?y0)) (at ?t ?x2 ?y0) (not (empty ?x2 ?y0))
    )
  )
  (:action move-type_4-e
   :parameters (?t ?x1 ?x2 ?x3 ?y1 ?y2)
   :precondition (and (type_4 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2) (at ?t ?x2 ?y1) (at ?t ?x2 ?y2)
        (adjwe ?x1 ?x2) (adjwe ?x2 ?x3)
        (adjns ?y1 ?y2)
        (empty ?x3 ?y1) (empty ?x3 ?y2)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x1 ?y2)) (empty ?x1 ?y2)
        (at ?t ?x3 ?y1) (not (empty ?x3 ?y1)) (at ?t ?x3 ?y2) (not (empty ?x3 ?y2))
    )
  )
  (:action move-type_4-w
   :parameters (?t ?x0 ?x1 ?x2 ?y1 ?y2)
   :precondition (and (type_4 ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2) (at ?t ?x2 ?y1) (at ?t ?x2 ?y2)
        (adjwe ?x0 ?x1) (adjwe ?x1 ?x2)
        (adjns ?y1 ?y2)
        (empty ?x0 ?y1) (empty ?x0 ?y2)
    )
   :effect (and 
        (not (at ?t ?x2 ?y1)) (empty ?x2 ?y1) (not (at ?t ?x2 ?y2)) (empty ?x2 ?y2)
        (at ?t ?x0 ?y1) (not (empty ?x0 ?y1)) (at ?t ?x0 ?y2) (not (empty ?x0 ?y2))
    )
  )
)

