(define (domain khunpan)
  (:requirements :strips)
  (:predicates (adjwe ?h1 ?h2) (adjns ?v1 ?v2) 
        (at ?t ?h ?v) (empty ?h ?v) 
        (tile_h ?t) (tile_o ?t) (tile_q ?t) (tile_v ?t)
  )
  (:action move-tile_h-s
   :parameters (?t ?x1 ?x2 ?y1 ?y2)
   :precondition (and (tile_h ?t)
        (at ?t ?x1 ?y1) (at ?t ?x2 ?y1)
        (adjwe ?x1 ?x2)
        (adjns ?y1 ?y2)
        (empty ?x1 ?y2) (empty ?x2 ?y2)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x2 ?y1)) (empty ?x2 ?y1)
        (at ?t ?x1 ?y2) (not (empty ?x1 ?y2)) (at ?t ?x2 ?y2) (not (empty ?x2 ?y2))
    )
  )
  (:action move-tile_h-n
   :parameters (?t ?x1 ?x2 ?y0 ?y1)
   :precondition (and (tile_h ?t)
        (at ?t ?x1 ?y1) (at ?t ?x2 ?y1)
        (adjwe ?x1 ?x2)
        (adjns ?y0 ?y1)
        (empty ?x1 ?y0) (empty ?x2 ?y0)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x2 ?y1)) (empty ?x2 ?y1)
        (at ?t ?x1 ?y0) (not (empty ?x1 ?y0)) (at ?t ?x2 ?y0) (not (empty ?x2 ?y0))
    )
  )
  (:action move-tile_h-e
   :parameters (?t ?x1 ?x2 ?x3 ?y1)
   :precondition (and (tile_h ?t)
        (at ?t ?x1 ?y1) (at ?t ?x2 ?y1)
        (adjwe ?x1 ?x2) (adjwe ?x2 ?x3)
        
        (empty ?x3 ?y1)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x3 ?y1) (not (empty ?x3 ?y1))
    )
  )
  (:action move-tile_h-w
   :parameters (?t ?x0 ?x1 ?x2 ?y1)
   :precondition (and (tile_h ?t)
        (at ?t ?x1 ?y1) (at ?t ?x2 ?y1)
        (adjwe ?x0 ?x1) (adjwe ?x1 ?x2)
        
        (empty ?x0 ?y1)
    )
   :effect (and 
        (not (at ?t ?x2 ?y1)) (empty ?x2 ?y1)
        (at ?t ?x0 ?y1) (not (empty ?x0 ?y1))
    )
  )
  (:action move-tile_o-s
   :parameters (?t ?x1 ?y1 ?y2)
   :precondition (and (tile_o ?t)
        (at ?t ?x1 ?y1)
        
        (adjns ?y1 ?y2)
        (empty ?x1 ?y2)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x1 ?y2) (not (empty ?x1 ?y2))
    )
  )
  (:action move-tile_o-n
   :parameters (?t ?x1 ?y0 ?y1)
   :precondition (and (tile_o ?t)
        (at ?t ?x1 ?y1)
        
        (adjns ?y0 ?y1)
        (empty ?x1 ?y0)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x1 ?y0) (not (empty ?x1 ?y0))
    )
  )
  (:action move-tile_o-e
   :parameters (?t ?x1 ?x2 ?y1)
   :precondition (and (tile_o ?t)
        (at ?t ?x1 ?y1)
        (adjwe ?x1 ?x2)
        
        (empty ?x2 ?y1)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x2 ?y1) (not (empty ?x2 ?y1))
    )
  )
  (:action move-tile_o-w
   :parameters (?t ?x0 ?x1 ?y1)
   :precondition (and (tile_o ?t)
        (at ?t ?x1 ?y1)
        (adjwe ?x0 ?x1)
        
        (empty ?x0 ?y1)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x0 ?y1) (not (empty ?x0 ?y1))
    )
  )
  (:action move-tile_q-s
   :parameters (?t ?x1 ?x2 ?y1 ?y2 ?y3)
   :precondition (and (tile_q ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2) (at ?t ?x2 ?y1) (at ?t ?x2 ?y2)
        (adjwe ?x1 ?x2)
        (adjns ?y1 ?y2) (adjns ?y2 ?y3)
        (empty ?x2 ?y3) (empty ?x1 ?y3)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x2 ?y1)) (empty ?x2 ?y1)
        (at ?t ?x2 ?y3) (not (empty ?x2 ?y3)) (at ?t ?x1 ?y3) (not (empty ?x1 ?y3))
    )
  )
  (:action move-tile_q-n
   :parameters (?t ?x1 ?x2 ?y0 ?y1 ?y2)
   :precondition (and (tile_q ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2) (at ?t ?x2 ?y1) (at ?t ?x2 ?y2)
        (adjwe ?x1 ?x2)
        (adjns ?y0 ?y1) (adjns ?y1 ?y2)
        (empty ?x1 ?y0) (empty ?x2 ?y0)
    )
   :effect (and 
        (not (at ?t ?x1 ?y2)) (empty ?x1 ?y2) (not (at ?t ?x2 ?y2)) (empty ?x2 ?y2)
        (at ?t ?x1 ?y0) (not (empty ?x1 ?y0)) (at ?t ?x2 ?y0) (not (empty ?x2 ?y0))
    )
  )
  (:action move-tile_q-e
   :parameters (?t ?x1 ?x2 ?x3 ?y1 ?y2)
   :precondition (and (tile_q ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2) (at ?t ?x2 ?y1) (at ?t ?x2 ?y2)
        (adjwe ?x1 ?x2) (adjwe ?x2 ?x3)
        (adjns ?y1 ?y2)
        (empty ?x3 ?y1) (empty ?x3 ?y2)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x1 ?y2)) (empty ?x1 ?y2)
        (at ?t ?x3 ?y1) (not (empty ?x3 ?y1)) (at ?t ?x3 ?y2) (not (empty ?x3 ?y2))
    )
  )
  (:action move-tile_q-w
   :parameters (?t ?x0 ?x1 ?x2 ?y1 ?y2)
   :precondition (and (tile_q ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2) (at ?t ?x2 ?y1) (at ?t ?x2 ?y2)
        (adjwe ?x0 ?x1) (adjwe ?x1 ?x2)
        (adjns ?y1 ?y2)
        (empty ?x0 ?y1) (empty ?x0 ?y2)
    )
   :effect (and 
        (not (at ?t ?x2 ?y1)) (empty ?x2 ?y1) (not (at ?t ?x2 ?y2)) (empty ?x2 ?y2)
        (at ?t ?x0 ?y1) (not (empty ?x0 ?y1)) (at ?t ?x0 ?y2) (not (empty ?x0 ?y2))
    )
  )
  (:action move-tile_v-s
   :parameters (?t ?x1 ?y1 ?y2 ?y3)
   :precondition (and (tile_v ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2)
        
        (adjns ?y1 ?y2) (adjns ?y2 ?y3)
        (empty ?x1 ?y3)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1)
        (at ?t ?x1 ?y3) (not (empty ?x1 ?y3))
    )
  )
  (:action move-tile_v-n
   :parameters (?t ?x1 ?y0 ?y1 ?y2)
   :precondition (and (tile_v ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2)
        
        (adjns ?y0 ?y1) (adjns ?y1 ?y2)
        (empty ?x1 ?y0)
    )
   :effect (and 
        (not (at ?t ?x1 ?y2)) (empty ?x1 ?y2)
        (at ?t ?x1 ?y0) (not (empty ?x1 ?y0))
    )
  )
  (:action move-tile_v-e
   :parameters (?t ?x1 ?x2 ?y1 ?y2)
   :precondition (and (tile_v ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2)
        (adjwe ?x1 ?x2)
        (adjns ?y1 ?y2)
        (empty ?x2 ?y1) (empty ?x2 ?y2)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x1 ?y2)) (empty ?x1 ?y2)
        (at ?t ?x2 ?y1) (not (empty ?x2 ?y1)) (at ?t ?x2 ?y2) (not (empty ?x2 ?y2))
    )
  )
  (:action move-tile_v-w
   :parameters (?t ?x0 ?x1 ?y1 ?y2)
   :precondition (and (tile_v ?t)
        (at ?t ?x1 ?y1) (at ?t ?x1 ?y2)
        (adjwe ?x0 ?x1)
        (adjns ?y1 ?y2)
        (empty ?x0 ?y1) (empty ?x0 ?y2)
    )
   :effect (and 
        (not (at ?t ?x1 ?y1)) (empty ?x1 ?y1) (not (at ?t ?x1 ?y2)) (empty ?x1 ?y2)
        (at ?t ?x0 ?y1) (not (empty ?x0 ?y1)) (at ?t ?x0 ?y2) (not (empty ?x0 ?y2))
    )
  )
)

